import mongoose from "mongoose";

/** @given by user
 * - job description : String
 * - resume text : String
 * - self description : String
 *
 * @generated by ai
 * - matchScore : Number
 * - technical question : [{
 *      question : "",
 *      intention : "",
 *       answer:""
 *                      }]
 *
 * - behavioral question : [{
 *      question : "",
 *      intention : "",
 *       answer:""
 *                       }]
 *
 * - skill gaps : [{
 *             skill : "",
 *              severity : {type: String, enum:["low", "medium", "high"]}
 *                 }]
 * - preparation plan : [{
 *
 *                 day : Number,
 *                 focus : String,
 *                  tasks: [string]
 *
 *                          }]
 *
 */
const technicalQuestionSchema = new mongoose.Schema(
  {
    question: {
      type: String,
      required: [true, "technical question is required"],
    },
    intention: { type: String, required: [true, "intention is required"] },
    answer: { type: String, required: [true, "answer is required"] },
  },
  { _id: false },
);

const behavioralQuestionSchema = new mongoose.Schema(
  {
    question: {
      type: String,
      required: [true, "technical question is required"],
    },
    intention: { type: String, required: [true, "intention is required"] },
    answer: { type: String, required: [true, "answer is required"] },
  },
  { _id: false },
);

const skillGapsSchema = new mongoose.Schema(
  {
    skill: { type: String, required: [true, "skill is required"] },
    severity: {
      type: String,
      enum: ["low", "medium", "high"],
      required: [true, "severity is required"],
    },
  },
  { _id: false },
);

const preparationPlanSchema = new mongoose.Schema({
  day: { type: Number, required: [true, "Day Number is required"] },
  focus: { type: String, required: [true, "focus is required"] },
  tasks: [{ type: String, required: [true, "Task is required"] }], //task is a array of string
});
const interviewReportSchema = new mongoose.Schema(
  {
    title: { type: String, required: [true, "title is required"] },
    jobDescription: {
      type: String,
      required: [true, "Job description is required"],
    },
    resume: { type: String },
    selfDescription: { type: String },
    matchScore: { type: Number, min: 0, max: 100 },
    technicalQuestions: [technicalQuestionSchema],
    behavioralQuestions: [behavioralQuestionSchema],
    skillGaps: [skillGapsSchema],
    preparationPlan: [preparationPlanSchema],
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "users",
    },
    //     metaData: {
    //     userId:    { type: mongoose.Schema.Types.ObjectId, ref: "users" },
    //     title:     { type: String, default: "Untitled Interview" }, // user-friendly label
    //     status:    { type: String, enum: ["pending", "completed", "failed"], default: "pending" },
    //     aiModel:   { type: String },         // e.g. "claude-sonnet-4-6"
    //     language:  { type: String, default: "en" },
    //     generatedAt: { type: Date },         // when AI finished generating
    //   }
  },
  { timestamps: true },
);

export const interviewReportModel = mongoose.model(
  "interviewReports",
  interviewReportSchema,
);
